{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "plugin",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.4.jar",
          "url": "plugin-1.0.4.jar",
          "size": 66820,
          "sha512": "0a319e7fbfe6ab092c0af0a4fb94774c337879e67c3d12748e82a04765618d58bc1dff7ff41c85453482bccdad394297c1f7c659c4318df2fde42e2ede8c7049",
          "sha256": "4be5930b690fd213e239bc33baa561d2440eb13c3506d2d4b12df43acb6f0027",
          "sha1": "292c08e09e0b742f05bdfd24ad6035e8957de876",
          "md5": "04da77febb9d38270e1d7efdaf66127d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "instances",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.4.jar",
          "url": "plugin-1.0.4.jar",
          "size": 66820,
          "sha512": "0a319e7fbfe6ab092c0af0a4fb94774c337879e67c3d12748e82a04765618d58bc1dff7ff41c85453482bccdad394297c1f7c659c4318df2fde42e2ede8c7049",
          "sha256": "4be5930b690fd213e239bc33baa561d2440eb13c3506d2d4b12df43acb6f0027",
          "sha1": "292c08e09e0b742f05bdfd24ad6035e8957de876",
          "md5": "04da77febb9d38270e1d7efdaf66127d"
        }
      ]
    }
  ]
}
