{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "instances",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.1.3.jar",
          "url": "instances-1.1.3.jar",
          "size": 3329,
          "sha512": "65f26276eb7c998ea5c6e66ca51d61c97a941f901ff199d3cf68bbd93c9510a061c3c9eec7b8e15554a9552bc5f9bccc0322c24d2ab7dfb3c1054e341863f18d",
          "sha256": "419311744a4eeb51d30e36d6bbd711f4001a3a5d86cc5cad99f7bd7c766849db",
          "sha1": "d3c60ff6ae9e7f806d35950d214a35e4c581159d",
          "md5": "0e67dea4197b9c568394efa55a22c277"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.1.3.jar",
          "url": "instances-1.1.3.jar",
          "size": 3329,
          "sha512": "65f26276eb7c998ea5c6e66ca51d61c97a941f901ff199d3cf68bbd93c9510a061c3c9eec7b8e15554a9552bc5f9bccc0322c24d2ab7dfb3c1054e341863f18d",
          "sha256": "419311744a4eeb51d30e36d6bbd711f4001a3a5d86cc5cad99f7bd7c766849db",
          "sha1": "d3c60ff6ae9e7f806d35950d214a35e4c581159d",
          "md5": "0e67dea4197b9c568394efa55a22c277"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.1.3-sources.jar",
          "url": "instances-1.1.3-sources.jar",
          "size": 1855,
          "sha512": "f01345a36bac8acebcfebcac1a4c7c15e689fff4d59c92bd20cd2f5b4916bc53f46703e181fb8fbd3b1e16f556111b083a1b064d74a980ee3dc5149d40a543dd",
          "sha256": "9a2d9c813bf9c8890fc01945235e0b7e97e330e21cf579bf932e8fe0445087ce",
          "sha1": "57ccf12ccf12c47a5a5da74f8a549900f69830b0",
          "md5": "8078cf1649486b54ad3313af10af6787"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.1.3-javadoc.jar",
          "url": "instances-1.1.3-javadoc.jar",
          "size": 261,
          "sha512": "1f77031e07c36596b9be89fc91d566fe3c9d4db61ff9db7f56646a8d723c6bd8209d8aef3d153b109801b9cad4230eb695ce4b8b7b3a695c1111d3078ef3ff4b",
          "sha256": "1aabe28883cdae1e7f0d4f81fda758ae338d246ecaa79fb890223aacff338b18",
          "sha1": "a0f61e5e5faf1951f4de85b5baa48485bf6b1eb3",
          "md5": "2d8decf70a45d1eeed7f7261b86bda0e"
        }
      ]
    }
  ]
}
