{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "json",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-1.1.3.jar",
          "url": "json-1.1.3.jar",
          "size": 3617,
          "sha512": "e221cc29b73a8b775573946fd636cd4a05114919c90ca191322895e0073bec19cd6442ffa3a90d7bd87f33121f7dbe5f42f77078a2952a0cad05a5300fc46b38",
          "sha256": "51b5061a21a0fad606d79f3efbdb1e90951dad84a085da8d4237a0a2deefd19d",
          "sha1": "0da6cdf9f9ef69d3febfa8a11a926ad72bb06bd8",
          "md5": "111a693e1dfa9cd4802a544eb90cdb83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "json-1.1.3.jar",
          "url": "json-1.1.3.jar",
          "size": 3617,
          "sha512": "e221cc29b73a8b775573946fd636cd4a05114919c90ca191322895e0073bec19cd6442ffa3a90d7bd87f33121f7dbe5f42f77078a2952a0cad05a5300fc46b38",
          "sha256": "51b5061a21a0fad606d79f3efbdb1e90951dad84a085da8d4237a0a2deefd19d",
          "sha1": "0da6cdf9f9ef69d3febfa8a11a926ad72bb06bd8",
          "md5": "111a693e1dfa9cd4802a544eb90cdb83"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "json-1.1.3-sources.jar",
          "url": "json-1.1.3-sources.jar",
          "size": 1208,
          "sha512": "e99b9fd645ba37ad4620fdb7c97a92f205a63a97dfcad5d269bd1344c0b8854e6c32a6c1b15238a58e813becfcd2aae29312e30417d78b8873cfea8865acbb61",
          "sha256": "4bd335cec58cc1b8317e463cd0fb81ad7b239617d583f9b94be9ef1675382adb",
          "sha1": "8bdcf63c9fc856789283b5f5d8e10d62e43160f9",
          "md5": "f991f7d5d68d524bb17e2537d72d12ae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "json-1.1.3-javadoc.jar",
          "url": "json-1.1.3-javadoc.jar",
          "size": 261,
          "sha512": "fe3afd61c9ac2245af1228e82e78b92b970f4819f9417dba66c18ce444da46fdfbee3b9679181701f73bb0e161cbbd41bc2cec476e8eec3bf40e1eed892b63cd",
          "sha256": "89d358ad93953c85312b8b9f7991213b386211f37327b9d7803dfb6d46707d84",
          "sha1": "d78138d70da453dfdb7db3584f207ad77df6d4a3",
          "md5": "9885011897bee0a2d60811e6c50ea311"
        }
      ]
    }
  ]
}
