{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "aidl",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "aidl-1.0.8.aar",
          "url": "aidl-1.0.8.aar",
          "size": 25758,
          "sha512": "33076d8e9d49b53f3aa7e03658a05b05e24895b444ced13e47e2ac93728f5a214ccffa472ecf0c9784712689e11c7e4397b36a0e38fa3be076469c1776995468",
          "sha256": "49ead552c27a819bfc2258c20ccd433227e312f25921788e373c7f65c6f2a49a",
          "sha1": "e8e5e2d398b2a35faebd2bff8248827acc03b8b9",
          "md5": "930bfc917982e540d75ab7eec3a0e30c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "aidl-1.0.8.aar",
          "url": "aidl-1.0.8.aar",
          "size": 25758,
          "sha512": "33076d8e9d49b53f3aa7e03658a05b05e24895b444ced13e47e2ac93728f5a214ccffa472ecf0c9784712689e11c7e4397b36a0e38fa3be076469c1776995468",
          "sha256": "49ead552c27a819bfc2258c20ccd433227e312f25921788e373c7f65c6f2a49a",
          "sha1": "e8e5e2d398b2a35faebd2bff8248827acc03b8b9",
          "md5": "930bfc917982e540d75ab7eec3a0e30c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aidl-1.0.8-sources.jar",
          "url": "aidl-1.0.8-sources.jar",
          "size": 7981,
          "sha512": "d826326935a4f940993fd60bdd7aca8cf27d672777c1f743ae90fc0e4ccccaa120571f55963e501ba6ae880746566cba4d1a830f9453e3c12351ebc0d746e8d6",
          "sha256": "986c1672aa61a622028581cadc9c8de962bf43bdcc9556b2922ef4c0d9fcf05d",
          "sha1": "e0977ad1c93b9322108669918ce2e612bc32c300",
          "md5": "1d4f4b1808c1a510200ab2422cb642b5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aidl-1.0.8-javadoc.jar",
          "url": "aidl-1.0.8-javadoc.jar",
          "size": 342495,
          "sha512": "06d7842cd309c0dfcf660e01c25c3fbab45edff63bf8e0c5fcb251141e8bb5b50dbb277305283d5dd90b837189ba6880c5df19b29e17c15a6ca603cce9931057",
          "sha256": "c63155d073e17c1eff4a7330625d6dcee85f679e3d9797146eea0940205b1de1",
          "sha1": "7d5b1aed432f8ed95c18f22cd3f0bbd04a5812ad",
          "md5": "81f65a710b6ed48940e0208bc4973156"
        }
      ]
    }
  ]
}
