{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "instances",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.10.jar",
          "url": "instances-1.0.10.jar",
          "size": 2597,
          "sha512": "be9824035f90c22278c91c06b407b4cab1073e4b71cf15b34e98422659f8cfbb8055c694210aec68ef48b015f7d58aa7563a5aed4670d51de67f9282efa9a9b9",
          "sha256": "b9244a42ad6469f0ad214871bf6d99ec8d4e8c1308eb779cb9de6e41c0531bde",
          "sha1": "923976f6f84b3fd8d45dc8c97248e226076a8b4c",
          "md5": "54a969416e3fca91fdf8b85fc76c8f2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.10.jar",
          "url": "instances-1.0.10.jar",
          "size": 2597,
          "sha512": "be9824035f90c22278c91c06b407b4cab1073e4b71cf15b34e98422659f8cfbb8055c694210aec68ef48b015f7d58aa7563a5aed4670d51de67f9282efa9a9b9",
          "sha256": "b9244a42ad6469f0ad214871bf6d99ec8d4e8c1308eb779cb9de6e41c0531bde",
          "sha1": "923976f6f84b3fd8d45dc8c97248e226076a8b4c",
          "md5": "54a969416e3fca91fdf8b85fc76c8f2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.10-sources.jar",
          "url": "instances-1.0.10-sources.jar",
          "size": 1523,
          "sha512": "586f897aab497c2e9a81c720a4ccfe70b96ca4a8bf13f6c17a34f15ba99c4ba24fda6e9e0662f6aa448948cccd95f92527add1736ddb2d5db15fce004baafe21",
          "sha256": "10bd3a57864885f6a35d7ea0a2a0371e1ca5be9da791a49cfc1470780101b7ce",
          "sha1": "945038098e5306294448f54f1bc7f22745e7ab9a",
          "md5": "eebe5c8691ec26940a7be1302852d5ff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.10-javadoc.jar",
          "url": "instances-1.0.10-javadoc.jar",
          "size": 261,
          "sha512": "8a9e818026f28b185f5e11524ad6a8e60f349daf59a379dbb996174a1d583c99e7f85f6970d63ac8ebc2fc487b4cc2500e7a0819e09b2f8f4bec4b1e5d9b2edf",
          "sha256": "df5dd4f04d27c880138de42cd68788b8bfcd93a4d3b8cecc2cfede527a8ee946",
          "sha1": "f97db030b788b03f305bcdf0b018e44382d09918",
          "md5": "de585a741a4d67c3464b9575d829601a"
        }
      ]
    }
  ]
}
