{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "plugin",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.8.jar",
          "url": "plugin-1.0.8.jar",
          "size": 66541,
          "sha512": "e8c58467a063eb50d514bd42d1efd38b93bebbb236c4abcdba2de18a280f76b82d6b72d67b5697a0113d9d3f2dba35a44ee23c3284ba911206a6434fa89fdaf6",
          "sha256": "52e9c4a46923aec9395b31f3be0f48358fa90d4a08c98cd68571fcbadcd23e40",
          "sha1": "3381b77a1420ffa4ae5024350ec6ec0c076660d8",
          "md5": "1c04dbaf8b8c802596cf0ec650914338"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "instances",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.8.jar",
          "url": "plugin-1.0.8.jar",
          "size": 66541,
          "sha512": "e8c58467a063eb50d514bd42d1efd38b93bebbb236c4abcdba2de18a280f76b82d6b72d67b5697a0113d9d3f2dba35a44ee23c3284ba911206a6434fa89fdaf6",
          "sha256": "52e9c4a46923aec9395b31f3be0f48358fa90d4a08c98cd68571fcbadcd23e40",
          "sha1": "3381b77a1420ffa4ae5024350ec6ec0c076660d8",
          "md5": "1c04dbaf8b8c802596cf0ec650914338"
        }
      ]
    }
  ]
}
