{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "aidl",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "aidl-1.0.6.aar",
          "url": "aidl-1.0.6.aar",
          "size": 25758,
          "sha512": "33076d8e9d49b53f3aa7e03658a05b05e24895b444ced13e47e2ac93728f5a214ccffa472ecf0c9784712689e11c7e4397b36a0e38fa3be076469c1776995468",
          "sha256": "49ead552c27a819bfc2258c20ccd433227e312f25921788e373c7f65c6f2a49a",
          "sha1": "e8e5e2d398b2a35faebd2bff8248827acc03b8b9",
          "md5": "930bfc917982e540d75ab7eec3a0e30c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "aidl-1.0.6.aar",
          "url": "aidl-1.0.6.aar",
          "size": 25758,
          "sha512": "33076d8e9d49b53f3aa7e03658a05b05e24895b444ced13e47e2ac93728f5a214ccffa472ecf0c9784712689e11c7e4397b36a0e38fa3be076469c1776995468",
          "sha256": "49ead552c27a819bfc2258c20ccd433227e312f25921788e373c7f65c6f2a49a",
          "sha1": "e8e5e2d398b2a35faebd2bff8248827acc03b8b9",
          "md5": "930bfc917982e540d75ab7eec3a0e30c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aidl-1.0.6-sources.jar",
          "url": "aidl-1.0.6-sources.jar",
          "size": 7981,
          "sha512": "d826326935a4f940993fd60bdd7aca8cf27d672777c1f743ae90fc0e4ccccaa120571f55963e501ba6ae880746566cba4d1a830f9453e3c12351ebc0d746e8d6",
          "sha256": "986c1672aa61a622028581cadc9c8de962bf43bdcc9556b2922ef4c0d9fcf05d",
          "sha1": "e0977ad1c93b9322108669918ce2e612bc32c300",
          "md5": "1d4f4b1808c1a510200ab2422cb642b5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aidl-1.0.6-javadoc.jar",
          "url": "aidl-1.0.6-javadoc.jar",
          "size": 342498,
          "sha512": "ce1417c49914d6459defa421156c5e5e6421c3011467756aee75ca2e7dc49f7fd44234e12b2b336e0004e501bf80afbfa9aef7cba525d1503d6c552669657708",
          "sha256": "d437a3d9a2baf4c314cbf15d240575dc017aa155d0a28f4e886db4c13f47448f",
          "sha1": "a9126b52e6a692d6a00bd8757f7bb1bbf192a7c3",
          "md5": "aab3d2e7497476ab2b5fd9e16745c86d"
        }
      ]
    }
  ]
}
