{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "annotations",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.2.jar",
          "url": "annotations-1.0.2.jar",
          "size": 3738,
          "sha512": "767bc61a496448c4d46ded26983465925d0fea086dcb993f67357721bf94bc2079c697f3f885c9121ceb816f86f44c881c3dc0307e160ec34e8afe2a837bd7a3",
          "sha256": "e04d6332c9bfeee8806eeccf810c02512c026b3989df484e02adbe1d5cc7c2ad",
          "sha1": "cbf2dd8ccc4f3344ba3f8437632291fe291f325a",
          "md5": "fd07dcdf4de92252166da6617df2b4e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.2.jar",
          "url": "annotations-1.0.2.jar",
          "size": 3738,
          "sha512": "767bc61a496448c4d46ded26983465925d0fea086dcb993f67357721bf94bc2079c697f3f885c9121ceb816f86f44c881c3dc0307e160ec34e8afe2a837bd7a3",
          "sha256": "e04d6332c9bfeee8806eeccf810c02512c026b3989df484e02adbe1d5cc7c2ad",
          "sha1": "cbf2dd8ccc4f3344ba3f8437632291fe291f325a",
          "md5": "fd07dcdf4de92252166da6617df2b4e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.2-sources.jar",
          "url": "annotations-1.0.2-sources.jar",
          "size": 2036,
          "sha512": "fe53fb890e18caa2652e468dd4216cf3031131dcf2f2f1cf29f5d08807664772f05136becba4a9d2512c6b521d9970132343229a0c8613bc3f8686fe7ee9fb6f",
          "sha256": "daa19cfcb1333c14a0db11221f1d998fba88278d5cbedcfcc2e96ebb2ff96613",
          "sha1": "1c000aa2a460210b37c14bd08c313bad02a53a25",
          "md5": "4c2078f097eabbab17ccd8ce4493d073"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.2-javadoc.jar",
          "url": "annotations-1.0.2-javadoc.jar",
          "size": 261,
          "sha512": "dd2f9abab5e65173a9fc4270a94b00f771dd604c0d11c914271d70e34fe2c86160f8d5c6ba83b6476841fb51db47fea0c05d10a0bf14367efd8d7d3c5dc37f77",
          "sha256": "7d5c85864b62ce9ad608322931bffc7d388420efb8df8c52c60fae50536715f4",
          "sha1": "3c68fa77e2fb34a72de1eec09d2405bda4c9f5d1",
          "md5": "928e047cb678d74ec216a38c523bdb2d"
        }
      ]
    }
  ]
}
