{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "plugin",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.6.jar",
          "url": "plugin-1.0.6.jar",
          "size": 66777,
          "sha512": "4c91e6d00bb6a738b67f0154c3091a9bb7919b895ecf8f9b5c99d496e0ab8b1c672de24075eb7089ff1aa34bf487960a3594606576feb7246451cd5bb928532a",
          "sha256": "7d14bc2e634c00203c8669f21b04011c55ac52fc22f559fe2b2f6a78a4dcf03d",
          "sha1": "96df8dbed61217dc0ee162fc8b4707259724518b",
          "md5": "2a429ee37c63b90ba2b5786f048e5fe8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "instances",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.6.jar",
          "url": "plugin-1.0.6.jar",
          "size": 66777,
          "sha512": "4c91e6d00bb6a738b67f0154c3091a9bb7919b895ecf8f9b5c99d496e0ab8b1c672de24075eb7089ff1aa34bf487960a3594606576feb7246451cd5bb928532a",
          "sha256": "7d14bc2e634c00203c8669f21b04011c55ac52fc22f559fe2b2f6a78a4dcf03d",
          "sha1": "96df8dbed61217dc0ee162fc8b4707259724518b",
          "md5": "2a429ee37c63b90ba2b5786f048e5fe8"
        }
      ]
    }
  ]
}
