{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "instances",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.4.jar",
          "url": "instances-1.0.4.jar",
          "size": 2597,
          "sha512": "254f36da0a8b83d00cf492ede2e1b3a9f17726bc45fd351219d4263113e629d416aa80ecda58157952fa3e37c41dc7966adc5700c88fdb50a80622de89ef472f",
          "sha256": "99049614435d308fa4505b924f1f405355d5dc14545d1f83698db1983b6a3396",
          "sha1": "37d9b4cb971eb537d694cd22e5ab2e93ab328aad",
          "md5": "75eae54267f97c632c535cd511dc0e07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.4.jar",
          "url": "instances-1.0.4.jar",
          "size": 2597,
          "sha512": "254f36da0a8b83d00cf492ede2e1b3a9f17726bc45fd351219d4263113e629d416aa80ecda58157952fa3e37c41dc7966adc5700c88fdb50a80622de89ef472f",
          "sha256": "99049614435d308fa4505b924f1f405355d5dc14545d1f83698db1983b6a3396",
          "sha1": "37d9b4cb971eb537d694cd22e5ab2e93ab328aad",
          "md5": "75eae54267f97c632c535cd511dc0e07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.4-sources.jar",
          "url": "instances-1.0.4-sources.jar",
          "size": 1523,
          "sha512": "2a1f364072e90186a5dbbc46f25733c54c7c895df64bfabd889c9d88e38a9e825d0e8a892f9b411541187900348f958ccf49b91b088c060403a4ebfef629cadc",
          "sha256": "586ae1cf6d87d4e3ca3bde0edfe3de63786517428e2f866c7946b22a7540e201",
          "sha1": "a9116c4ac062e9380f53e3ca06c83c9320ab35a5",
          "md5": "585edf9c1d1960bda00effd06683cb10"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.4-javadoc.jar",
          "url": "instances-1.0.4-javadoc.jar",
          "size": 261,
          "sha512": "6731c41cefbbc842d3c8010d5f1ce6dce6f19f6e318bf2db8cc480f198fa9772e9c7c8f5c3230039fdffaf5e5242614b15c0d044ad3bb327d2a03e6e28dea9e5",
          "sha256": "0fe93b9ad329c775eff01223af595757fee4cbd666623af0e746c97f75dc5c52",
          "sha1": "860a70944995428f295c685aa0fe5d9458e7ca19",
          "md5": "5ae1166774de73e191c4b9ed8a58f007"
        }
      ]
    }
  ]
}
