{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "annotations",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.8.jar",
          "url": "annotations-1.0.8.jar",
          "size": 3738,
          "sha512": "c9552770d053f77a39f2c2092361ddfa66065bae3da842f62578b07880827496d643d80778b5c0d06a370be13a52390673f925a674eae3e448c1aa07aef06420",
          "sha256": "f54afe3793ed6e8779fd9730201878e5d8f68a484dd9868cef1a3e93e58d25db",
          "sha1": "b91ae32c9e73648667e1f56dec0ef62b9466aef7",
          "md5": "4b757c198ba7fc645c34d84e59b926ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.8.jar",
          "url": "annotations-1.0.8.jar",
          "size": 3738,
          "sha512": "c9552770d053f77a39f2c2092361ddfa66065bae3da842f62578b07880827496d643d80778b5c0d06a370be13a52390673f925a674eae3e448c1aa07aef06420",
          "sha256": "f54afe3793ed6e8779fd9730201878e5d8f68a484dd9868cef1a3e93e58d25db",
          "sha1": "b91ae32c9e73648667e1f56dec0ef62b9466aef7",
          "md5": "4b757c198ba7fc645c34d84e59b926ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.8-sources.jar",
          "url": "annotations-1.0.8-sources.jar",
          "size": 2036,
          "sha512": "35d54387ab76d18dcdc3228690fbf97af98f4d1b463ea4788764d549cf91d1fdbe6441efe191dcfd1b05ae53531c59a913b9604ed8c9d6da7c892e4c52260693",
          "sha256": "e3fb46eba61738eb483bb79949e479a105bf35ea12fb4863747f58116e458629",
          "sha1": "ff4f43d2489766bc2cc72240d6829172cf08c590",
          "md5": "28f8429c4f8159f6c3ff130016bb507e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.8-javadoc.jar",
          "url": "annotations-1.0.8-javadoc.jar",
          "size": 261,
          "sha512": "afd8d131f8b08c0de3078e163a5a0c2ce04c98bb251baf23d255017ba3936bbe6913d14d957867e721ffbf02d80c249dcfa4bcab03fa6e900b74888864a9295e",
          "sha256": "a9442408f2599dbfc2bad5054ac2ca549501f35a1df4a84f83faf5dcf7ced8ba",
          "sha1": "559baebb0f9640365233603cb2078810be0cf9b0",
          "md5": "cee0153d2a86e0896aecd6b26c1253f1"
        }
      ]
    }
  ]
}
