{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "plugin",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.10.jar",
          "url": "plugin-1.0.10.jar",
          "size": 66530,
          "sha512": "ff7cbec3e16929e91872c84a629f22e3dc2e3d72a6a84981563cd69b662d988ef32f14cb9fbb8e38d2f29fd0e071925fac197f461eebc3aba8384bc5b91017b1",
          "sha256": "f804795aac7237f3f5d49f430421944a5650a8c2d4cd3f12ea2595a38464060f",
          "sha1": "25632deefdbb2624eeadf85000f192e085d67096",
          "md5": "766f818a96e9894443d875c14a099520"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "instances",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.10.jar",
          "url": "plugin-1.0.10.jar",
          "size": 66530,
          "sha512": "ff7cbec3e16929e91872c84a629f22e3dc2e3d72a6a84981563cd69b662d988ef32f14cb9fbb8e38d2f29fd0e071925fac197f461eebc3aba8384bc5b91017b1",
          "sha256": "f804795aac7237f3f5d49f430421944a5650a8c2d4cd3f12ea2595a38464060f",
          "sha1": "25632deefdbb2624eeadf85000f192e085d67096",
          "md5": "766f818a96e9894443d875c14a099520"
        }
      ]
    }
  ]
}
