{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "annotations",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.3.jar",
          "url": "annotations-1.0.3.jar",
          "size": 3738,
          "sha512": "a9966df1c4fc6d29e21cfb376b88f16e89067ae1b1f5e8790edd71f9ff98ec415c90b1d9bbaeee1aef6d50f7425a4feb54af5feb66be71c8f97f7803f43f8122",
          "sha256": "ee4aaae03bc1518a161f3fe6f94f28448cb8eb5e3cbb6b3c9a29622034829503",
          "sha1": "5c982cc389fe231220ce2435404ac3f95f3307c9",
          "md5": "2bff5b826fdb151161c2b822196fa372"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.3.jar",
          "url": "annotations-1.0.3.jar",
          "size": 3738,
          "sha512": "a9966df1c4fc6d29e21cfb376b88f16e89067ae1b1f5e8790edd71f9ff98ec415c90b1d9bbaeee1aef6d50f7425a4feb54af5feb66be71c8f97f7803f43f8122",
          "sha256": "ee4aaae03bc1518a161f3fe6f94f28448cb8eb5e3cbb6b3c9a29622034829503",
          "sha1": "5c982cc389fe231220ce2435404ac3f95f3307c9",
          "md5": "2bff5b826fdb151161c2b822196fa372"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.3-sources.jar",
          "url": "annotations-1.0.3-sources.jar",
          "size": 2036,
          "sha512": "432855c7d3720de4fe0e93eb08f7670e4ec8df61c580eb51815fe3bc68f596f2b51c8bf1f506c4c08341a212656df2d5b18eafa936d9dcb5bd1a073f207ac007",
          "sha256": "d43617452d0edf25a64f39dedf247ea4737def627c9e986948e6ffc6518970e4",
          "sha1": "804d46cc8ca334a17c79c07938c0ccf520c8bb6e",
          "md5": "c5db43ea6c946a4e639916cf063fc9da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.3-javadoc.jar",
          "url": "annotations-1.0.3-javadoc.jar",
          "size": 261,
          "sha512": "d97edb98a45c12e9cbbeadc052b990ebfa42e078d002301eefbf3d60532d371793101863fcd7723a1a692890b2842ca9beb3b54510a2fa7af05b025e143d392f",
          "sha256": "05dbabde927be29830c0acdfdd2b2639dbbfbcac4a7ed643e6141e7a0adfd804",
          "sha1": "089afbe5d03e61b58639fb45ef81bbb189f1c8bc",
          "md5": "0cbed215bfa1a7c0079d36eaf9817059"
        }
      ]
    }
  ]
}
