{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "app",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseAabPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.libraryelements": "aab"
      },
      "files": [
        {
          "name": "app-1.0.11.aab",
          "url": "app-1.0.11.aab",
          "size": 3759330,
          "sha512": "eabae03801085e524ec662b0171de7d2d71e9fadf8d116921f2d425ce7c68bcb24849dd132fb477653329ecce54fa269dc74880f7ad56b7a4661c6b4d21ef137",
          "sha256": "e957d4716476b1aeeeb26b827ddc397223e0d12f6ac16ab76a3e9fb385ac28ac",
          "sha1": "1a10d58916ac7a663b48c1405ae1969f022e2948",
          "md5": "fceb24d465937afef3ad1fe37fe70dd2"
        }
      ]
    }
  ]
}
