{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "client",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-1.0.9.aar",
          "url": "client-1.0.9.aar",
          "size": 45495,
          "sha512": "94eceff5b336889bd6c7e6c7a6d8570dfb60992caf0cec1912cce1993301caf4038560e2781b2110b63d4c424f9c190cfb7e3d1926943a419d99999d7168db39",
          "sha256": "4931c1904403ac53882e2b5391cdbfdddf92aa8c58e71466e51aedca8242ffdc",
          "sha1": "83699a6ac48cc30eb72bafd01fc71d566624bb23",
          "md5": "64be747b242227fac8bc5ae79bd7c7aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "aidl",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "instances",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-1.0.9.aar",
          "url": "client-1.0.9.aar",
          "size": 45495,
          "sha512": "94eceff5b336889bd6c7e6c7a6d8570dfb60992caf0cec1912cce1993301caf4038560e2781b2110b63d4c424f9c190cfb7e3d1926943a419d99999d7168db39",
          "sha256": "4931c1904403ac53882e2b5391cdbfdddf92aa8c58e71466e51aedca8242ffdc",
          "sha1": "83699a6ac48cc30eb72bafd01fc71d566624bb23",
          "md5": "64be747b242227fac8bc5ae79bd7c7aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-1.0.9-sources.jar",
          "url": "client-1.0.9-sources.jar",
          "size": 13625,
          "sha512": "815ea23a14c72018bffe6108583cfcf2e26d29c82d32c4410ae626aafa6e6f2efeb9e2f9f1b6118f2b21334ac869452d69a2d707eddb4674a829696018f19504",
          "sha256": "456c0e289b6280208f0a255e9322e6d24f714e0a81a49bb20bbbb1d3d36fc0fa",
          "sha1": "899ad6155c33c61b2ad556b89f33b03364d40c49",
          "md5": "e57279a3716392e456a862a45d1f267e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-1.0.9-javadoc.jar",
          "url": "client-1.0.9-javadoc.jar",
          "size": 393926,
          "sha512": "566f73aeb398206fb41ec806c06c7247deb66ba8c318ce40bcf77b3a6b852940853c8dadd89f13b76c65f0b32d50a24148620470b589b1cffe64527bac45dbc0",
          "sha256": "a897862c263752eeb65d6dd251e34ca8d3056f90400a6ab5295f4d168be2ffd2",
          "sha1": "04e2ffd80afdb3f047ff8d17b1f0911a5044520d",
          "md5": "8a549f3e00ac2c99ae39132c042c9615"
        }
      ]
    }
  ]
}
