{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "plugin",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.1.5.jar",
          "url": "plugin-1.1.5.jar",
          "size": 77528,
          "sha512": "86f341c2212f1eafc8dc8c7bb35248a0363176d460f9b91ba689e03a5a507dcd7f023e80fb5a93f542f63ce44e2d6453ade3ef80a171165ce1da282750665773",
          "sha256": "3f9109e7856575ead6fde138a70e888e93a072963afb17526393c3feb4844256",
          "sha1": "534b3f4999f079014e5f4cb433e0e4c190364353",
          "md5": "9070873e8f9154f07991c2d9eda16e1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.okafke.aapi",
          "module": "api",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "instances",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "json",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.1.5.jar",
          "url": "plugin-1.1.5.jar",
          "size": 77528,
          "sha512": "86f341c2212f1eafc8dc8c7bb35248a0363176d460f9b91ba689e03a5a507dcd7f023e80fb5a93f542f63ce44e2d6453ade3ef80a171165ce1da282750665773",
          "sha256": "3f9109e7856575ead6fde138a70e888e93a072963afb17526393c3feb4844256",
          "sha1": "534b3f4999f079014e5f4cb433e0e4c190364353",
          "md5": "9070873e8f9154f07991c2d9eda16e1f"
        }
      ]
    }
  ]
}
