{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "plugin",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.9.jar",
          "url": "plugin-1.0.9.jar",
          "size": 66530,
          "sha512": "f7c790d8adebdc2153e4e1880229889c978f9474c7e156d909b842bcf8cf765ed4a174726791e62cb0c12637aa9ed0b75310dd0128a86ce2695009f2b72441ee",
          "sha256": "ef460ea23f4ba72e620c1561035573f0883257436b862369faa94da8b5e89887",
          "sha1": "3534bd2b76c1391619993322d736895dd2c9d908",
          "md5": "3c6f01e21d26da6d43ab105cc59410f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "instances",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.9.jar",
          "url": "plugin-1.0.9.jar",
          "size": 66530,
          "sha512": "f7c790d8adebdc2153e4e1880229889c978f9474c7e156d909b842bcf8cf765ed4a174726791e62cb0c12637aa9ed0b75310dd0128a86ce2695009f2b72441ee",
          "sha256": "ef460ea23f4ba72e620c1561035573f0883257436b862369faa94da8b5e89887",
          "sha1": "3534bd2b76c1391619993322d736895dd2c9d908",
          "md5": "3c6f01e21d26da6d43ab105cc59410f0"
        }
      ]
    }
  ]
}
