{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "annotations",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.7.jar",
          "url": "annotations-1.0.7.jar",
          "size": 3738,
          "sha512": "bfc62ccf0f0c8364168474e6396ad52892a817004cf635fe6db0ea79b256541403576b87494e8697b3809a9be190d106e5521610e1374140d021189892df6528",
          "sha256": "083a17714bf6784fb1ea82498eb51fef5251000a7b83710b91a8e83126fac76e",
          "sha1": "db6a20de76200445cb30797afe89c241f3479e4f",
          "md5": "7254493d7a23f8b4e329457e40bd6d98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.7.jar",
          "url": "annotations-1.0.7.jar",
          "size": 3738,
          "sha512": "bfc62ccf0f0c8364168474e6396ad52892a817004cf635fe6db0ea79b256541403576b87494e8697b3809a9be190d106e5521610e1374140d021189892df6528",
          "sha256": "083a17714bf6784fb1ea82498eb51fef5251000a7b83710b91a8e83126fac76e",
          "sha1": "db6a20de76200445cb30797afe89c241f3479e4f",
          "md5": "7254493d7a23f8b4e329457e40bd6d98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.7-sources.jar",
          "url": "annotations-1.0.7-sources.jar",
          "size": 2036,
          "sha512": "9e27b07b805e3915bb2a242ef2c658ab27732d013842a0c815ce8a2b78576e72981722831169f93583da636345097a16e721e722ef72201314c7bb5a10cf3aaa",
          "sha256": "62a6444c8c3f433a2fe0c1fd1608865edee329f37d4a1795c93d071b1681deb9",
          "sha1": "f133ff0407e381f455d8514d358313300cc197eb",
          "md5": "34e92c9e1072a5e7ff824e9bfb1cd4f9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.7-javadoc.jar",
          "url": "annotations-1.0.7-javadoc.jar",
          "size": 261,
          "sha512": "ba061d1fd49f4d1c0fa5218e701cbe1ce9553fb03914781daced0a9d33f19915a40a6373540f017a8dbb6d48a3aa793c3279560bf0f875a85bde5637a8f4db8d",
          "sha256": "9bcbfd44d00c4794ebac470f16b1c92b129529ec705051b92c366cb780de3c71",
          "sha1": "4231544df6502e01dcedbcfcc42b62ad0413bf37",
          "md5": "bdde96dc7346509a8fd18916a1af2ff3"
        }
      ]
    }
  ]
}
