{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "plugin",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.1.3.jar",
          "url": "plugin-1.1.3.jar",
          "size": 76268,
          "sha512": "41ae993a67b23f13ce33338fa4a99bbff53b5b9751d7b65ca4819150eb2203d48bc2b60e241c5152772fd6d7247efdb5a5be3f6bd5ef03cbeae00d6937470043",
          "sha256": "ea087dc97abbf7fe22c3b5ce0245280aa07c721b7f02973c33a635035c099bf1",
          "sha1": "4399e28bab22977252c54359564d28f1ef244052",
          "md5": "2ce381e5686f5fa60f97b7cdda217393"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.okafke.aapi",
          "module": "api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "instances",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "json",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.1.3.jar",
          "url": "plugin-1.1.3.jar",
          "size": 76268,
          "sha512": "41ae993a67b23f13ce33338fa4a99bbff53b5b9751d7b65ca4819150eb2203d48bc2b60e241c5152772fd6d7247efdb5a5be3f6bd5ef03cbeae00d6937470043",
          "sha256": "ea087dc97abbf7fe22c3b5ce0245280aa07c721b7f02973c33a635035c099bf1",
          "sha1": "4399e28bab22977252c54359564d28f1ef244052",
          "md5": "2ce381e5686f5fa60f97b7cdda217393"
        }
      ]
    }
  ]
}
