{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "instances",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.2.jar",
          "url": "instances-1.0.2.jar",
          "size": 2597,
          "sha512": "0911df713decbf108957d0eb4e0a5500359517ad14b758d28b66f0d5a55a78a0babb1aebe7fae2e387e183b273e5cb2cabf605e692b7c4382e1d1fe600dcb74f",
          "sha256": "e4ce1dbb59ee7c2ec73db6d6887141bb8d1bb0def9c9dc3c45b2705544626264",
          "sha1": "d1cde3e191f9f9ee887a69eddf58d0fc83e4d8ce",
          "md5": "62ecd741f3b7fc13ee03e8d21e73b923"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.2.jar",
          "url": "instances-1.0.2.jar",
          "size": 2597,
          "sha512": "0911df713decbf108957d0eb4e0a5500359517ad14b758d28b66f0d5a55a78a0babb1aebe7fae2e387e183b273e5cb2cabf605e692b7c4382e1d1fe600dcb74f",
          "sha256": "e4ce1dbb59ee7c2ec73db6d6887141bb8d1bb0def9c9dc3c45b2705544626264",
          "sha1": "d1cde3e191f9f9ee887a69eddf58d0fc83e4d8ce",
          "md5": "62ecd741f3b7fc13ee03e8d21e73b923"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.2-sources.jar",
          "url": "instances-1.0.2-sources.jar",
          "size": 1523,
          "sha512": "92b769325cd76f816ddc9f6582c9dcf80e616864c45996945341cc7d00610644efbf413ba588a74a01425e6f400de9efb83bdbd67326e22a40670abe768a0171",
          "sha256": "181992458e8635d3faf1e5b70d18142616287ad0ba7ccb45f8adab006e3bb659",
          "sha1": "b4a2407286c98a8066da6e3285f6e4e32c4bae05",
          "md5": "da626668b3cf1283e6c58f8a3220c5bd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.2-javadoc.jar",
          "url": "instances-1.0.2-javadoc.jar",
          "size": 261,
          "sha512": "dd2f9abab5e65173a9fc4270a94b00f771dd604c0d11c914271d70e34fe2c86160f8d5c6ba83b6476841fb51db47fea0c05d10a0bf14367efd8d7d3c5dc37f77",
          "sha256": "7d5c85864b62ce9ad608322931bffc7d388420efb8df8c52c60fae50536715f4",
          "sha1": "3c68fa77e2fb34a72de1eec09d2405bda4c9f5d1",
          "md5": "928e047cb678d74ec216a38c523bdb2d"
        }
      ]
    }
  ]
}
