{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "client",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-1.1.0.aar",
          "url": "client-1.1.0.aar",
          "size": 46440,
          "sha512": "69c90f97e83db4bbe9f13e59b328f03fb186dceb42cfcec5d2f771a0490f2d11e6fc64ca8248dc98eb162c42bb29b98e1b8ad9729413e771d336a3dc315a0a54",
          "sha256": "54404246557cac23885a7971ba2f7ab11857dc9c8dbbd09f4015e3e340b398df",
          "sha1": "a84e18f05506d69fa5fa1ba7d71dbf37b7dce55c",
          "md5": "fea89cbe7a527e7320420a8369645a6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "aidl",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "instances",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-1.1.0.aar",
          "url": "client-1.1.0.aar",
          "size": 46440,
          "sha512": "69c90f97e83db4bbe9f13e59b328f03fb186dceb42cfcec5d2f771a0490f2d11e6fc64ca8248dc98eb162c42bb29b98e1b8ad9729413e771d336a3dc315a0a54",
          "sha256": "54404246557cac23885a7971ba2f7ab11857dc9c8dbbd09f4015e3e340b398df",
          "sha1": "a84e18f05506d69fa5fa1ba7d71dbf37b7dce55c",
          "md5": "fea89cbe7a527e7320420a8369645a6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-1.1.0-sources.jar",
          "url": "client-1.1.0-sources.jar",
          "size": 13890,
          "sha512": "6da371fc1bd5db3e49cd9081e1044cdf2256b934df172000b59ad1ea926e161f319f7659f40a21a3b4cb4ae37bcfc11be3a04137e99924d79f2b7497bf030dce",
          "sha256": "36148c711d91fce23b1af203171841453834b9647b84d7d58503efd437cb87e6",
          "sha1": "e9aa13160edef7eb07fea8e6ed7c9cd9389c495d",
          "md5": "da63fef8980cf2d448abf82f70defbe0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-1.1.0-javadoc.jar",
          "url": "client-1.1.0-javadoc.jar",
          "size": 392079,
          "sha512": "257bc1865784efa5184326665ec388d248665d2659f35fc2279bef608a66711840577e4f7ad27814427fdd0b0042c6ea4f8d02b165c14124a3f1cd8cbf143398",
          "sha256": "0192e55707e14b253a5f53f7749921a14df8c8540d4f0dd904813681f39705f4",
          "sha1": "213668d1ce590f5a250a6ca044fd16becd7f5197",
          "md5": "fb041a5913e09ba6e80965e8ecd8e706"
        }
      ]
    }
  ]
}
