{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "client",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-1.1.0.aar",
          "url": "client-1.1.0.aar",
          "size": 46600,
          "sha512": "99dafc6ea0ddd6da09eb9f44bb2d49be0d75805263e0106c7214194d466c219dd0fd0e0c24aaad686d24dbbc097c1dec347ce5cac3d70847ebe415e16ced1139",
          "sha256": "5ac2105214d7a813fd13b375421e5ca10dd29f29363b203ecbffbcb16ad83bd5",
          "sha1": "34cede8b7fb8f7bad77347fe98df96521d61e3fa",
          "md5": "382e22878114d59ed2f0d603d562df13"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "aidl",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "instances",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-1.1.0.aar",
          "url": "client-1.1.0.aar",
          "size": 46600,
          "sha512": "99dafc6ea0ddd6da09eb9f44bb2d49be0d75805263e0106c7214194d466c219dd0fd0e0c24aaad686d24dbbc097c1dec347ce5cac3d70847ebe415e16ced1139",
          "sha256": "5ac2105214d7a813fd13b375421e5ca10dd29f29363b203ecbffbcb16ad83bd5",
          "sha1": "34cede8b7fb8f7bad77347fe98df96521d61e3fa",
          "md5": "382e22878114d59ed2f0d603d562df13"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-1.1.0-sources.jar",
          "url": "client-1.1.0-sources.jar",
          "size": 13916,
          "sha512": "b30cdba8bbae9a9eb50a0bd270c588e18189f0420d1382ccf5c821a71099e689153ff6b5a2f33d88041ec493f1d401c698396dd5da3d9f25c3c2335626e25de1",
          "sha256": "8dd48b102b971e09ac12aa79c5f25138c980dd6dc21d2f3bcd8de4281ab5c642",
          "sha1": "10acb2e011698383127385adc47ab038b43f60bb",
          "md5": "a95ddccc5fe5f14de422205b9bbd72dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-1.1.0-javadoc.jar",
          "url": "client-1.1.0-javadoc.jar",
          "size": 392592,
          "sha512": "e2ae0be24c3bcb399d98a166fe61bdbb52fe7cfca72769c234db9445809c5321fd7ecba72cb9c62512ebef68046018bc0159f406c630f8ea112d06e751b1b334",
          "sha256": "61734386cc901d18fecfa0ee24a6e7a5a17568f8aedd32252d9cb4e3ca40e6a3",
          "sha1": "ff433fae0eb20f8c2ca36fbc4af963881a95155a",
          "md5": "b2e9e15584251949aa76c3e27eaccc5a"
        }
      ]
    }
  ]
}
