{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "app",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseAabPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.libraryelements": "aab"
      },
      "files": [
        {
          "name": "app-1.0.10.aab",
          "url": "app-1.0.10.aab",
          "size": 3759512,
          "sha512": "37852d5e561788daf5aebf4e3c3b2574912a72f17b43200beea81a15b37813bec7272e8f573a31f434651bf6fe0ecaa2e55e54759526840859adae0b3f76bade",
          "sha256": "7b830fffccdccf1e337534744934f5e11287b9bbd80fc8dd526189a7d4e7f5d3",
          "sha1": "52856b40914de5e88681527baecc515847f8abbf",
          "md5": "678c2521469d5fc80caf1de9684f1e4b"
        }
      ]
    }
  ]
}
