{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "annotations",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.9.jar",
          "url": "annotations-1.0.9.jar",
          "size": 3738,
          "sha512": "114770c5927eb20859647fe95961526699df48adc360283630963871853e4b8fd2ab876881b91def04d2bd1a2372a4397bf1dcb892b48bb86d4eeb20344d83db",
          "sha256": "c08562527b1c342c3f351d5ffd3de2b84ac81895cab708029c08b16f76bbc738",
          "sha1": "dab919b9949d9f27fb5fe109492b0d787b718036",
          "md5": "2126e4f7421adc7b804f04cb30e9b196"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.9.jar",
          "url": "annotations-1.0.9.jar",
          "size": 3738,
          "sha512": "114770c5927eb20859647fe95961526699df48adc360283630963871853e4b8fd2ab876881b91def04d2bd1a2372a4397bf1dcb892b48bb86d4eeb20344d83db",
          "sha256": "c08562527b1c342c3f351d5ffd3de2b84ac81895cab708029c08b16f76bbc738",
          "sha1": "dab919b9949d9f27fb5fe109492b0d787b718036",
          "md5": "2126e4f7421adc7b804f04cb30e9b196"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.9-sources.jar",
          "url": "annotations-1.0.9-sources.jar",
          "size": 2036,
          "sha512": "a4b9c44dc53501ca607342a8e8c0d0c806110773d6bb56d88182098fac1eab8fac3be46329087eebacbc9b783fabfe908788b4d42bb98e30c1ae639c7650bcf2",
          "sha256": "730e1a8250cacd725d1614fc0ca7f56e8b787ad71fbef1f2d68f1c4d352cffbc",
          "sha1": "4764b975b5928b27c9d59f05b5b53eb3d038ba00",
          "md5": "46227cd46886da95d4dadda1d102ea07"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.9-javadoc.jar",
          "url": "annotations-1.0.9-javadoc.jar",
          "size": 261,
          "sha512": "c7afdb19bd23ceddb1dcbddaa9aeb3bfa61c306f78af728e6fb94192c835162c9f480568ac91ab0b9a5b26fbc73ea7959b940b9b698368e3f47fc44bb759033d",
          "sha256": "f476991a18bcdff459339a52b54039c43f23cbe148bf0250201a146e8bc62f92",
          "sha1": "3b04676c4fed6e05991f2c9b90fa9a98c811f087",
          "md5": "f726265ea557acc2cddf59c891fd005c"
        }
      ]
    }
  ]
}
