{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "client",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-1.0.10.aar",
          "url": "client-1.0.10.aar",
          "size": 45498,
          "sha512": "602cc3653d022bf24f98bba2bf1ae1d100eabfe88428f96504bbad6180b2a86b8fefe4dcfeb51f6d0f4e22eceb5b034ed45d1b34c80a070c6580253e208c3718",
          "sha256": "a593fcc254c4b0a19adde68a8f6bc2d067f49324ddd0aefca6e5c84ce53ea992",
          "sha1": "5a154a6515b38d6ac6f8d744ab25670e9d01c6f7",
          "md5": "d79710afc11b8e128b5e9d5673f808d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "aidl",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "instances",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-1.0.10.aar",
          "url": "client-1.0.10.aar",
          "size": 45498,
          "sha512": "602cc3653d022bf24f98bba2bf1ae1d100eabfe88428f96504bbad6180b2a86b8fefe4dcfeb51f6d0f4e22eceb5b034ed45d1b34c80a070c6580253e208c3718",
          "sha256": "a593fcc254c4b0a19adde68a8f6bc2d067f49324ddd0aefca6e5c84ce53ea992",
          "sha1": "5a154a6515b38d6ac6f8d744ab25670e9d01c6f7",
          "md5": "d79710afc11b8e128b5e9d5673f808d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-1.0.10-sources.jar",
          "url": "client-1.0.10-sources.jar",
          "size": 13625,
          "sha512": "815ea23a14c72018bffe6108583cfcf2e26d29c82d32c4410ae626aafa6e6f2efeb9e2f9f1b6118f2b21334ac869452d69a2d707eddb4674a829696018f19504",
          "sha256": "456c0e289b6280208f0a255e9322e6d24f714e0a81a49bb20bbbb1d3d36fc0fa",
          "sha1": "899ad6155c33c61b2ad556b89f33b03364d40c49",
          "md5": "e57279a3716392e456a862a45d1f267e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-1.0.10-javadoc.jar",
          "url": "client-1.0.10-javadoc.jar",
          "size": 393937,
          "sha512": "c01481aeadbc469366640ed3728756b592ff9dcec21b4ce3a33c110dd7aee8ca4d63d87803b9d5c2d6e73f1cbdbac1e77521a76ef050363e233270daa0918fe8",
          "sha256": "1e97db6e8662897c73ce87b8b63b3ec32235d8100ce71ca20613014374dc5618",
          "sha1": "70fa0bff653e5f65cebcae4775f342b8a3572747",
          "md5": "bd5ffd34a51ba0fbea4060dea3b3069f"
        }
      ]
    }
  ]
}
