{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "instances",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.3.jar",
          "url": "instances-1.0.3.jar",
          "size": 2597,
          "sha512": "d9beafecc6a61e14cb7ab45debf6c1f8ff83d2cd8db75b7e3196dccd4ae2e54d3fe84a3e5ea85e31f61c9a906c7b3f0348d02248b480d3a7103ac02d55ef5e0c",
          "sha256": "f41ff322b4c65108fffb8fc5376264c07c19c112b4dbb182b7012bf596cfe343",
          "sha1": "65b02920aa058cfc0c6400ad040b2a991a4b843f",
          "md5": "edb9de99320bab8118317b67f1d1ca47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.3.jar",
          "url": "instances-1.0.3.jar",
          "size": 2597,
          "sha512": "d9beafecc6a61e14cb7ab45debf6c1f8ff83d2cd8db75b7e3196dccd4ae2e54d3fe84a3e5ea85e31f61c9a906c7b3f0348d02248b480d3a7103ac02d55ef5e0c",
          "sha256": "f41ff322b4c65108fffb8fc5376264c07c19c112b4dbb182b7012bf596cfe343",
          "sha1": "65b02920aa058cfc0c6400ad040b2a991a4b843f",
          "md5": "edb9de99320bab8118317b67f1d1ca47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.3-sources.jar",
          "url": "instances-1.0.3-sources.jar",
          "size": 1523,
          "sha512": "7b6111e2bcaab92d28ba39bd57f6c5c4555412492da08d3b921425e9708888b404b8d806c2b2ca7a357813c47bfde58e697fe0c1b0266a3da724413bb83c2dc4",
          "sha256": "c8f8a82a3f3b46cb2dba558c9c40883410c586c0336520ddf6f32357184a0360",
          "sha1": "25352c3deb353399040ab160996acc3a35a87b63",
          "md5": "17487288a671350e191bc2e21b6247ef"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.3-javadoc.jar",
          "url": "instances-1.0.3-javadoc.jar",
          "size": 261,
          "sha512": "d97edb98a45c12e9cbbeadc052b990ebfa42e078d002301eefbf3d60532d371793101863fcd7723a1a692890b2842ca9beb3b54510a2fa7af05b025e143d392f",
          "sha256": "05dbabde927be29830c0acdfdd2b2639dbbfbcac4a7ed643e6141e7a0adfd804",
          "sha1": "089afbe5d03e61b58639fb45ef81bbb189f1c8bc",
          "md5": "0cbed215bfa1a7c0079d36eaf9817059"
        }
      ]
    }
  ]
}
