{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "annotations",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.6.jar",
          "url": "annotations-1.0.6.jar",
          "size": 3738,
          "sha512": "545986a7f14cf4a4e1b6d34bd9d9dd71e613063e5971b319551432492b4e5eb4741e43a21388e1303da11b5e2a4faeceedc3e1adb2fe31f9a30fdda4b1dfe005",
          "sha256": "52934f8cd38cafc795bf140049a591d4c2fd5d2887ebbcb065d2d61563e4389a",
          "sha1": "2e14a64d49a3ef4a6b17b803c9085d5f355baf46",
          "md5": "b8d6c1bf2b8c75c5c9846334bcb42035"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.6.jar",
          "url": "annotations-1.0.6.jar",
          "size": 3738,
          "sha512": "545986a7f14cf4a4e1b6d34bd9d9dd71e613063e5971b319551432492b4e5eb4741e43a21388e1303da11b5e2a4faeceedc3e1adb2fe31f9a30fdda4b1dfe005",
          "sha256": "52934f8cd38cafc795bf140049a591d4c2fd5d2887ebbcb065d2d61563e4389a",
          "sha1": "2e14a64d49a3ef4a6b17b803c9085d5f355baf46",
          "md5": "b8d6c1bf2b8c75c5c9846334bcb42035"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.6-sources.jar",
          "url": "annotations-1.0.6-sources.jar",
          "size": 2036,
          "sha512": "e25b5fa216e007657a228e128a1d6e386917b8329baf17e936c8be6b9ceb5e777814c3629b49060cb3aa8529354e44fc90ccb99efad7a4a0a498a1a9ea1f6da4",
          "sha256": "093137557dc6ea5bd408da096277eae986a701d80cd8a7a63d99fd2e37a96b7a",
          "sha1": "3b068dcd3897abd5315f874ec8cc2735470c9d28",
          "md5": "44046ec770205a9f822075dc8a6156d1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.6-javadoc.jar",
          "url": "annotations-1.0.6-javadoc.jar",
          "size": 261,
          "sha512": "546129f769370e82f204915738460885c4a1715755d7d22463e6615b96050d0a8ce91eccb6a610df06f1cc0b664ca54e91e54ae81c4a7c18bb18fbed4cc283d5",
          "sha256": "44f0e84077beb15ab539a2344fd26ff09afddf45d1eb07cfdca505cd18711357",
          "sha1": "853466745d489ae35b86c91a4051738dc337c150",
          "md5": "efe35640a4377b52e9f954fb3f76f721"
        }
      ]
    }
  ]
}
