{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "keyboard",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseAabPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.libraryelements": "aab"
      },
      "files": [
        {
          "name": "keyboard-1.1.0.aab",
          "url": "keyboard-1.1.0.aab",
          "size": 4476009,
          "sha512": "3962e101983f332f3dab46a48f75280d747e7082ee551334f660bbe53e61691096799bcb591349ca8a4e30bcd4b4115b7ac841ee0ea74bfb7f84da33f868e2bf",
          "sha256": "f383827769a5f467ae31e69c4958bf7ec0444f08ec0486595893389856b339c8",
          "sha1": "28133abbaa2ce9c8bb7bf216434af3d32d965c59",
          "md5": "f7413ab21f58ff72959ce139f8c07e5d"
        }
      ]
    }
  ]
}
