{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "plugin",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.7.jar",
          "url": "plugin-1.0.7.jar",
          "size": 66810,
          "sha512": "411196a721c9a23b72d96ffc5a19cc559bd05100b7b5e225527c26cf80572848c6f388cf4eba5ced56b00f5a90e594748f2d51c54c615a999d85da686204648e",
          "sha256": "a2ea2eac566c86b4391a172b8d1e386bd0a7a70ac3fd41c0aeb52d00d64546be",
          "sha1": "0c908d04b1363c917ad34d6ae0195dd724bb37e4",
          "md5": "3fcc97138caab2e28fc375a37b21e02a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "instances",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.7.jar",
          "url": "plugin-1.0.7.jar",
          "size": 66810,
          "sha512": "411196a721c9a23b72d96ffc5a19cc559bd05100b7b5e225527c26cf80572848c6f388cf4eba5ced56b00f5a90e594748f2d51c54c615a999d85da686204648e",
          "sha256": "a2ea2eac566c86b4391a172b8d1e386bd0a7a70ac3fd41c0aeb52d00d64546be",
          "sha1": "0c908d04b1363c917ad34d6ae0195dd724bb37e4",
          "md5": "3fcc97138caab2e28fc375a37b21e02a"
        }
      ]
    }
  ]
}
