{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "annotations",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.4.jar",
          "url": "annotations-1.0.4.jar",
          "size": 3738,
          "sha512": "8a87e2ef77aa398c4f66f7e5bd73e61db34efe8ebe721aba0ef4cbbd870df9f86d2320d21205f44cdfd77040e19185bf1966c100cb498e4b8607c89ac27f920c",
          "sha256": "46106a395b7d0105123ef846b5ba51cbdf6c81b1d14b0e6d3db2e8f4c7ab4093",
          "sha1": "ebab6134c7532f450a1836a016cc8222a9d58944",
          "md5": "8288142c90fb80daa355963b80c94c15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.4.jar",
          "url": "annotations-1.0.4.jar",
          "size": 3738,
          "sha512": "8a87e2ef77aa398c4f66f7e5bd73e61db34efe8ebe721aba0ef4cbbd870df9f86d2320d21205f44cdfd77040e19185bf1966c100cb498e4b8607c89ac27f920c",
          "sha256": "46106a395b7d0105123ef846b5ba51cbdf6c81b1d14b0e6d3db2e8f4c7ab4093",
          "sha1": "ebab6134c7532f450a1836a016cc8222a9d58944",
          "md5": "8288142c90fb80daa355963b80c94c15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.4-sources.jar",
          "url": "annotations-1.0.4-sources.jar",
          "size": 2036,
          "sha512": "0012d7e383b0f1274358d5493c2b0919adedb4213b9ab3e42715ef2ce9176214dc492abe82c12f0855857e9bf7e972712756617e32d38ff60a8f289820b11126",
          "sha256": "360d11ddb9737e66a05031e965ca9ec4a7f93889a621b715bb5528f1693d6b96",
          "sha1": "57bcae18eb50b914ddc9e52e2f557144d3e363eb",
          "md5": "aedfb125b10ad3c43cfbb5dfd1d5500d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-1.0.4-javadoc.jar",
          "url": "annotations-1.0.4-javadoc.jar",
          "size": 261,
          "sha512": "f33bdcec18f32b5bedcd70ae4df647167a32993d5f771af3dd378877b562c158c29ea36f34e81e1dd0eaf15b668025f32bb2a3e7c3722038c6b567167a829c8a",
          "sha256": "91430b8a5902eb492fc468afff85eb93bc0bf247cd98b45fcac05ca9332f3183",
          "sha1": "77d6a7668b211ec06137c188a77dcec8a7f02480",
          "md5": "b40d19bc8e333dd1a6944c991b84fa33"
        }
      ]
    }
  ]
}
