{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "instances",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.7.jar",
          "url": "instances-1.0.7.jar",
          "size": 2597,
          "sha512": "5a769b1e745b04145468a37c445e334c46da4436509e47cab9b4392ade208d2d74eb89bd7f4657bc1d54b5112e97c1eefcb9beebb4fe12cb518af27d1cbc99bf",
          "sha256": "125903b739004a8a966975ffe3be08b3516d810b0924031b7a63499caf526737",
          "sha1": "411c20013472e96312cc353f27078c1d63552aaa",
          "md5": "0f00806829bbfd46f6b3491def24b4e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.7.jar",
          "url": "instances-1.0.7.jar",
          "size": 2597,
          "sha512": "5a769b1e745b04145468a37c445e334c46da4436509e47cab9b4392ade208d2d74eb89bd7f4657bc1d54b5112e97c1eefcb9beebb4fe12cb518af27d1cbc99bf",
          "sha256": "125903b739004a8a966975ffe3be08b3516d810b0924031b7a63499caf526737",
          "sha1": "411c20013472e96312cc353f27078c1d63552aaa",
          "md5": "0f00806829bbfd46f6b3491def24b4e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.7-sources.jar",
          "url": "instances-1.0.7-sources.jar",
          "size": 1523,
          "sha512": "f49c7c78f9f22a5e9ed64a1834ae4d24298c749ef55fc8896c32ce185d573ebb7d558a44f1b0e065715d18d0f6b100e8bfea8b466f78c8dca6d7c164e9aaad41",
          "sha256": "cae2d31bed35d6c6e999c4f64c71125122342055fb5f62dfaea066672465fec7",
          "sha1": "648ee45f570fbd06cd86a7defb375bcfe9c50d6d",
          "md5": "13067691a092be0b93668d3ad6646e3d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.7-javadoc.jar",
          "url": "instances-1.0.7-javadoc.jar",
          "size": 261,
          "sha512": "ba061d1fd49f4d1c0fa5218e701cbe1ce9553fb03914781daced0a9d33f19915a40a6373540f017a8dbb6d48a3aa793c3279560bf0f875a85bde5637a8f4db8d",
          "sha256": "9bcbfd44d00c4794ebac470f16b1c92b129529ec705051b92c366cb780de3c71",
          "sha1": "4231544df6502e01dcedbcfcc42b62ad0413bf37",
          "md5": "bdde96dc7346509a8fd18916a1af2ff3"
        }
      ]
    }
  ]
}
