{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi.plugin",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 62499,
          "sha512": "ec637938a86f72541a5a1e7391f87379dcf2886a05d15005270f136fa6b6bdb333b14ecbe2963c931e770d56e6aa7927925f711ada452e2d60e689140e71950d",
          "sha256": "5aaf80a7d6c5448cbb60f85b4a8ff6dd803603c9e6f0b33c1c50889537b63fb0",
          "sha1": "0d5feac1676aeb1a8e78af657e8caa5ac9564f4c",
          "md5": "0c3167c3e9d4f1e95c1491cf5a56b186"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "io.github.okafke.aapi.annotations",
          "module": "annotations",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.okafke.aapi.instances",
          "module": "instances",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 62499,
          "sha512": "ec637938a86f72541a5a1e7391f87379dcf2886a05d15005270f136fa6b6bdb333b14ecbe2963c931e770d56e6aa7927925f711ada452e2d60e689140e71950d",
          "sha256": "5aaf80a7d6c5448cbb60f85b4a8ff6dd803603c9e6f0b33c1c50889537b63fb0",
          "sha1": "0d5feac1676aeb1a8e78af657e8caa5ac9564f4c",
          "md5": "0c3167c3e9d4f1e95c1491cf5a56b186"
        }
      ]
    }
  ]
}
