{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "instances",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.0.jar",
          "url": "instances-1.0.0.jar",
          "size": 2597,
          "sha512": "b89d65dc1e5c1c37a0f595bd31f19165de27f9424991ea41034bccd84ee971e08c6d562dd75f2f5b3108ba2e4bab7d49813a6a41470bddd9e8ae324ebf0e8a84",
          "sha256": "c949991f0a5f4fe406ae21e1f80be04f6f47a5017b5ff0c078cd72ca9012e29c",
          "sha1": "675cf65186dc94f2813bb086448d7636e27330f8",
          "md5": "13cd018ce78ec707664bdfc7b7b7f59a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.0.jar",
          "url": "instances-1.0.0.jar",
          "size": 2597,
          "sha512": "b89d65dc1e5c1c37a0f595bd31f19165de27f9424991ea41034bccd84ee971e08c6d562dd75f2f5b3108ba2e4bab7d49813a6a41470bddd9e8ae324ebf0e8a84",
          "sha256": "c949991f0a5f4fe406ae21e1f80be04f6f47a5017b5ff0c078cd72ca9012e29c",
          "sha1": "675cf65186dc94f2813bb086448d7636e27330f8",
          "md5": "13cd018ce78ec707664bdfc7b7b7f59a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.0-sources.jar",
          "url": "instances-1.0.0-sources.jar",
          "size": 1523,
          "sha512": "c479786ecf18bd5e3e975efd0503d11dca9e0f0be61792baab7b75a5d11b5533011efa9578397776382979f1a88668d90c622d563ace19a52be7c31a08f3740b",
          "sha256": "d00d45f5f615183b0ffde9ee8a38424e5d8d9b518a087e18d58784e37c8714b4",
          "sha1": "85c071827b5ee8568223ffa3db60c8e1212b2ffe",
          "md5": "0f86b5bf65b3616bb631dccf45b8c511"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.0-javadoc.jar",
          "url": "instances-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "d24dde6f058f19f7e7bc3edf4e82d8ea87027b50521fbbf383a7f62d7f4906f9f640ac9ca2a4663cafb8483fa13d2dacf5c41b6379fcaeabd6a38bbf46f4c029",
          "sha256": "236f573a815662f937be86b8a6db915b59b571f238180fd6f78dc4b7ba17fb7d",
          "sha1": "74e2868bffd49ad2652a26e326b7b81d24569161",
          "md5": "b49a99378c5c27d69bba88fedf17ad75"
        }
      ]
    }
  ]
}
