{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "instances",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.1.jar",
          "url": "instances-1.0.1.jar",
          "size": 2597,
          "sha512": "b5bfb0c3fe2c46297b801e371cf77b5fe192566d259f7918f64690d94fa767f2147e2acc64869c79e7be8575ff2ddaec1d0886cae2edb27f4682482575041d51",
          "sha256": "70e12cc19c70499f19fa512aa7caf44bc513c255393e62fbf3c6ba2ecaef83db",
          "sha1": "ddfd47919188eff6a11d3b956a3bb2477d1b6093",
          "md5": "87d576f619f9fbe9230d61af2444e981"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "instances-1.0.1.jar",
          "url": "instances-1.0.1.jar",
          "size": 2597,
          "sha512": "b5bfb0c3fe2c46297b801e371cf77b5fe192566d259f7918f64690d94fa767f2147e2acc64869c79e7be8575ff2ddaec1d0886cae2edb27f4682482575041d51",
          "sha256": "70e12cc19c70499f19fa512aa7caf44bc513c255393e62fbf3c6ba2ecaef83db",
          "sha1": "ddfd47919188eff6a11d3b956a3bb2477d1b6093",
          "md5": "87d576f619f9fbe9230d61af2444e981"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.1-sources.jar",
          "url": "instances-1.0.1-sources.jar",
          "size": 1523,
          "sha512": "4df723a523dfc8cedf53395f2ff1d75f5ee361b2807c22d42044b0fe5f8c34412336f4c708bcbbb62cbc1613f836f075b7da56b82dbd1e4ea23ca7f2089590cd",
          "sha256": "5b5b2e9f594ea34c881214c41921dbea7aa84931e5928793a25693ed45a7493c",
          "sha1": "ccbd96993b8d431ae81a5b4d111d5419480f638d",
          "md5": "fc68a2473120a2d863ebd42fe963ab6b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "instances-1.0.1-javadoc.jar",
          "url": "instances-1.0.1-javadoc.jar",
          "size": 261,
          "sha512": "ce4a9dabe6419c7aec8f62fbc76d87cf1c116df56bec7bf3d545535d6e1063bba14bcaa0543d573b4610e9484342a9d60f92ce96bb081531f7c7d19e4baee123",
          "sha256": "f5c2b2c5bfbd9e8eb7297d5ce9ff5518c9670b4f4329dbe36b124e24bdaea71e",
          "sha1": "1d89ddf0edd1897d8b18527e0372a13b80fc14ad",
          "md5": "3ea68b3e22880e7123f1d2ab0055243d"
        }
      ]
    }
  ]
}
