{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.okafke.aapi",
    "module": "client-commons",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-commons-1.0.11.aar",
          "url": "client-commons-1.0.11.aar",
          "size": 22071,
          "sha512": "66cfb71ecca57e100c2206bafacf89c66d411a7c674cb40c6b1e2613951406a1bad12f5975f113e740ec900595de0ddc15d38f919d0b238df9a226b138b090e6",
          "sha256": "20738d5dfe61f4d2189b570a0e33dbd784718fc5a328a8e4b7de9a9163205cd6",
          "sha1": "c3a6bd0789ab00f9ed8fdac90225e65634fd80e4",
          "md5": "7b2a76344762fe58e12a63febb4e8318"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.okafke.aapi",
          "module": "annotations",
          "version": {
            "requires": "1.0.11"
          }
        },
        {
          "group": "io.github.okafke.aapi",
          "module": "client",
          "version": {
            "requires": "1.0.11"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-commons-1.0.11.aar",
          "url": "client-commons-1.0.11.aar",
          "size": 22071,
          "sha512": "66cfb71ecca57e100c2206bafacf89c66d411a7c674cb40c6b1e2613951406a1bad12f5975f113e740ec900595de0ddc15d38f919d0b238df9a226b138b090e6",
          "sha256": "20738d5dfe61f4d2189b570a0e33dbd784718fc5a328a8e4b7de9a9163205cd6",
          "sha1": "c3a6bd0789ab00f9ed8fdac90225e65634fd80e4",
          "md5": "7b2a76344762fe58e12a63febb4e8318"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-commons-1.0.11-sources.jar",
          "url": "client-commons-1.0.11-sources.jar",
          "size": 5539,
          "sha512": "2dfdad44eefc5d969e5cbb2168a446bc2807d2ef850e9afae4851ae04a1565101c83c634acf4f3c0602dbbaef7eff8c6f53147f2460d81e1b3ea955bfff28206",
          "sha256": "aaf07f352cc16774b85002442f80d91bbc6ec39548b2906b70c974ca60641764",
          "sha1": "d04c94a68927f24bd8b37a2d5d566da6edcd385b",
          "md5": "7789a3a4e9764b9fdf83b3efd3583c3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-commons-1.0.11-javadoc.jar",
          "url": "client-commons-1.0.11-javadoc.jar",
          "size": 307066,
          "sha512": "87fee0f64c3a80f8e6627bf0b907911c3e87b930dbce5d0414f2582c223a26067c22b2d56b04b49f7a7fcf0455280a36f314becb9b7103ab60b06f7e6d68a0a6",
          "sha256": "af75bed6d386b0bf09785886105241042e1f0d02c61862f7cac764422c266ae4",
          "sha1": "9d82f73730e9047a26e81f820c622b512a0ae91b",
          "md5": "50b3092d4460b6958428afbedcd7611d"
        }
      ]
    }
  ]
}
